
"use client";

import { useEffect, useState } from "react";
import type { WeeklySchedule, ScheduleEntry } from "@/types";
import { useAuth } from "@/hooks/use-auth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowRight, CalendarCheck, BusFront, UserCog, Settings as SettingsIcon, AlertTriangle } from "lucide-react";
import ScheduleConfirmationCard from "@/components/student/schedule-confirmation-card";
import { format, addDays, getDay } from 'date-fns';
import { tr } from 'date-fns/locale';
import { getStudentSchedule } from "@/lib/database";

interface NextRideInfo {
  studentName: string;
  pickupTime: string;
  dropoffTime: string;
  notificationMessage: string;
  relevantDate: string;
  rideDate: string; // ISO date string for API
  hasRide: boolean;
}

const daysOrder: ScheduleEntry["dayOfWeek"][] = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];


export default function DashboardPage() {
  const { user, isLoading: authIsLoading } = useAuth();
  const [nextRideInfo, setNextRideInfo] = useState<NextRideInfo | null>(null);
  const [isScheduleLoading, setIsScheduleLoading] = useState(true);

  useEffect(() => {
    if (user && user.role === "student" && user.weeklyScheduleId) {
      setIsScheduleLoading(true);
      const loadSchedule = async () => {
        try {
          // Fetch schedule from Supabase
          const studentSchedule = await getStudentSchedule(user.weeklyScheduleId!);

          let rideFound = false;
          let checkDate = new Date();
          let relevantDateObject = addDays(new Date(), 1);
          let relevantDateFormatted = "";
          let pickupTime = "";
          let dropoffTime = "";
          let notificationMessage = "";

          if (studentSchedule && studentSchedule.entries.length > 0) {
            for (let i = 1; i <= 7; i++) {
              checkDate = addDays(new Date(), i);
              const dayName = daysOrder[getDay(checkDate)];
              const entriesForDay = studentSchedule.entries
                .filter(entry => entry.dayOfWeek === dayName)
                .sort((a, b) => a.startTime.localeCompare(b.startTime));

              if (entriesForDay.length > 0) {
                relevantDateObject = checkDate;
                relevantDateFormatted = format(relevantDateObject, "dd MMMM yyyy, EEEE", { locale: tr });
                pickupTime = entriesForDay[0].startTime;
                dropoffTime = entriesForDay[entriesForDay.length - 1].endTime;
                // In a real app, this message would be generated by Genkit based on actual analysis
                notificationMessage = `Merhaba ${user.name}, ${relevantDateFormatted} için servisiniz planlanmıştır. Tahmini okulda olma saatiniz ${pickupTime}, okuldan ayrılış saatiniz ise ${dropoffTime} olacaktır. Lütfen servis saatleri için ayrıca onayınızı bekleyin.`;
                rideFound = true;
                break;
              }
            }
          }

          if (rideFound) {
            setNextRideInfo({
              studentName: user.name,
              pickupTime,
              dropoffTime,
              notificationMessage,
              relevantDate: relevantDateFormatted,
              rideDate: format(relevantDateObject, "yyyy-MM-dd"),
              hasRide: true,
            });
          } else {
            // Default message if no ride in the next 7 days
            setNextRideInfo({
              studentName: user.name,
              pickupTime: "N/A",
              dropoffTime: "N/A",
              notificationMessage: `Merhaba ${user.name}, önümüzdeki 7 gün için planlanmış bir servisiniz bulunmamaktadır.`,
              relevantDate: "Yakın Zamanda Servis Yok",
              rideDate: "",
              hasRide: false,
            });
          }
        } catch (error) {
          console.error("Error processing schedule for dashboard:", error);
          setNextRideInfo({
            studentName: user.name,
            pickupTime: "Hata",
            dropoffTime: "Hata",
            notificationMessage: `Merhaba ${user.name}, servis bilgileriniz yüklenirken bir sorun oluştu.`,
            relevantDate: format(addDays(new Date(), 1), "dd MMMM yyyy, EEEE", { locale: tr }),
            rideDate: "",
            hasRide: false,
          });
        } finally {
          setIsScheduleLoading(false);
        }
      };
      loadSchedule();
    } else if (user && user.role !== "student") {
      setIsScheduleLoading(false);
    } else if (!user && !authIsLoading) {
      setIsScheduleLoading(false);
    }
  }, [user, authIsLoading]);


  if (authIsLoading) {
    return (
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Yükleniyor...</CardTitle>
          </CardHeader>
          <CardContent>
            <p>Kullanıcı bilgileri yükleniyor, lütfen bekleyin.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!user) return null;

  return (
    <div className="space-y-6">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="text-3xl">Hoş Geldiniz, {user.name}!</CardTitle>
          <CardDescription>
            UniRide Assist kontrol paneline hoş geldiniz. Buradan ilgili işlemleri yapabilirsiniz.
          </CardDescription>
        </CardHeader>
      </Card>

      {user.role === "student" && (
        <>
          {isScheduleLoading && <Card><CardHeader><CardTitle>Servis Bilgileri Yükleniyor</CardTitle></CardHeader><CardContent><p>Ders programınız ve yaklaşan servis bilgileriniz kontrol ediliyor...</p></CardContent></Card>}
          {!isScheduleLoading && nextRideInfo && nextRideInfo.hasRide && (
            <ScheduleConfirmationCard {...nextRideInfo} />
          )}
          {!isScheduleLoading && nextRideInfo && !nextRideInfo.hasRide && (
            <Card className="bg-muted/50 border-border">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <AlertTriangle className="h-6 w-6 text-yellow-500" />
                  Servis Durumu
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">{nextRideInfo.notificationMessage}</p>
              </CardContent>
            </Card>
          )}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><CalendarCheck className="text-primary" />Hızlı İşlemler</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Link href="/schedule" passHref>
                <Button variant="outline" className="w-full justify-between py-6 text-left">
                  <div>
                    <h3 className="font-semibold">Ders Programım</h3>
                    <p className="text-sm text-muted-foreground">Haftalık programını görüntüle ve düzenle.</p>
                  </div>
                  <ArrowRight />
                </Button>
              </Link>
              <Link href="/request-ride" passHref>
                <Button variant="outline" className="w-full justify-between py-6 text-left">
                  <div>
                    <h3 className="font-semibold">Anlık Servis Talebi</h3>
                    <p className="text-sm text-muted-foreground">Program dışı servis ihtiyacın için talep oluştur.</p>
                  </div>
                  <ArrowRight />
                </Button>
              </Link>
            </CardContent>
          </Card>
        </>
      )}

      {user.role === "admin" && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><UserCog className="text-primary" />Yönetim Paneli</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Link href="/admin/vehicles" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                  <h3 className="font-semibold">Araç Yönetimi</h3>
                  <p className="text-sm text-muted-foreground">Servis araçlarını yönet.</p>
                </div>
                <BusFront />
              </Button>
            </Link>
            <Link href="/admin/users" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                  <h3 className="font-semibold">Kullanıcı Yönetimi</h3>
                  <p className="text-sm text-muted-foreground">Öğrenci ve admin hesaplarını yönet.</p>
                </div>
                <UserCog />
              </Button>
            </Link>
            <Link href="/admin/ride-requests" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                  <h3 className="font-semibold">Servis Talepleri</h3>
                  <p className="text-sm text-muted-foreground">Gelen servis taleplerini onayla/reddet.</p>
                </div>
                <CalendarCheck />
              </Button>
            </Link>
            <Link href="/admin/settings" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                  <h3 className="font-semibold">Genel Ayarlar</h3>
                  <p className="text-sm text-muted-foreground">Bildirim ve sistem ayarlarını yapılandır.</p>
                </div>
                <SettingsIcon />
              </Button>
            </Link>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
