
"use client";

import { useEffect, useState } from "react";
import { useTranslations } from 'next-intl';
import type { WeeklySchedule, ScheduleEntry } from "@/types";
import { useAuth } from "@/hooks/use-auth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { ArrowRight, CalendarCheck, BusFront, UserCog, Settings as SettingsIcon, AlertTriangle } from "lucide-react";
import ScheduleConfirmationCard from "@/components/student/schedule-confirmation-card";
import { format, addDays, getDay } from 'date-fns';
import { tr } from 'date-fns/locale';
import { getStudentSchedule } from "@/lib/database";

interface NextRideInfo {
  studentName: string;
  pickupTime: string;
  dropoffTime: string;
  notificationMessage: string;
  relevantDate: string;
  rideDate: string; // ISO date string for API
  hasRide: boolean;
}

const daysOrder: ScheduleEntry["dayOfWeek"][] = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];


export default function DashboardPage() {
  const t = useTranslations('page.admin.dashboard');
  const tc = useTranslations('common');
  const { user, isLoading: authIsLoading } = useAuth();
  const [nextRideInfo, setNextRideInfo] = useState<NextRideInfo | null>(null);
  const [isScheduleLoading, setIsScheduleLoading] = useState(true);

  useEffect(() => {
    if (user && user.role === "student" && user.weeklyScheduleId) {
      const loadSchedule = async () => {
        try {
          // Fetch schedule from Supabase
          const studentSchedule = await getStudentSchedule(user.weeklyScheduleId!);

          let rideFound = false;
          let checkDate = new Date();
          let relevantDateObject = addDays(new Date(), 1);
          let relevantDateFormatted = "";
          let pickupTime = "";
          let dropoffTime = "";
          let notificationMessage = "";

          if (studentSchedule && studentSchedule.entries.length > 0) {
            for (let i = 1; i <= 7; i++) {
              checkDate = addDays(new Date(), i);
              const dayName = daysOrder[getDay(checkDate)];
              const entriesForDay = studentSchedule.entries
                .filter(entry => entry.dayOfWeek === dayName)
                .sort((a, b) => a.startTime.localeCompare(b.startTime));

              if (entriesForDay.length > 0) {
                relevantDateObject = checkDate;
                relevantDateFormatted = format(relevantDateObject, "dd MMMM yyyy, EEEE", { locale: tr });
                pickupTime = entriesForDay[0].startTime;
                dropoffTime = entriesForDay[entriesForDay.length - 1].endTime;
                // In a real app, this message would be generated by Genkit based on actual analysis
                notificationMessage = `${tc('sidebar.dashboard')} ${user.name}`;
                rideFound = true;
                break;
              }
            }
          }

          if (rideFound) {
            setNextRideInfo({
              studentName: user.name,
              pickupTime,
              dropoffTime,
              notificationMessage,
              relevantDate: relevantDateFormatted,
              rideDate: format(relevantDateObject, "yyyy-MM-dd"),
              hasRide: true,
            });
          } else {
            // Default message if no ride in the next 7 days
            setNextRideInfo({
              studentName: user.name,
              pickupTime: "N/A",
              dropoffTime: "N/A",
              notificationMessage: `${tc('sidebar.dashboard')} ${user.name}`,
              relevantDate: tc('noResults'),
              rideDate: "",
              hasRide: false,
            });
          }
        } catch (error) {
          console.error("Error processing schedule for dashboard:", error);
          setNextRideInfo({
            studentName: user.name,
            pickupTime: tc('error'),
            dropoffTime: tc('error'),
            notificationMessage: `${tc('sidebar.dashboard')} ${user.name}`,
            relevantDate: format(addDays(new Date(), 1), "dd MMMM yyyy, EEEE", { locale: tr }),
            rideDate: "",
            hasRide: false,
          });
        } finally {
          setIsScheduleLoading(false);
        }
      };
      loadSchedule();
    } else if (user && user.role !== "student") {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- sync initial loading state once auth resolves (not a data fetch)
      setIsScheduleLoading(false);
    } else if (!user && !authIsLoading) {
      setIsScheduleLoading(false);
    }
  }, [user, authIsLoading]);


  if (authIsLoading) {
    return (
      <div className="space-y-6">
        <Card>
          <CardHeader>
          <CardTitle>{tc('loading')}</CardTitle>
        </CardHeader>
        <CardContent>
          <p>{tc('loading')}</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!user) return null;

  return (
    <div className="space-y-6">
      <Card className="shadow-lg">
        <CardHeader>
          <CardTitle className="text-3xl">{tc('sidebar.dashboard')}, {user.name}!</CardTitle>
          <CardDescription>
            {tc('sidebar.dashboard')}
          </CardDescription>
        </CardHeader>
      </Card>

      {user.role === "student" && (
        <>
          {isScheduleLoading && <Card><CardHeader><CardTitle>{tc('loading')}</CardTitle></CardHeader><CardContent><p>{tc('loading')}</p></CardContent></Card>}
          {!isScheduleLoading && nextRideInfo && nextRideInfo.hasRide && (
            <ScheduleConfirmationCard {...nextRideInfo} />
          )}
          {!isScheduleLoading && nextRideInfo && !nextRideInfo.hasRide && (
            <Card className="bg-muted/50 border-border">
              <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-xl">
                    <AlertTriangle className="h-6 w-6 text-yellow-500" />
                    {tc('sidebar.dashboard')}
                  </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">{nextRideInfo.notificationMessage}</p>
              </CardContent>
            </Card>
          )}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2"><CalendarCheck className="text-primary" />{tc('details')}</CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Link href="/schedule" passHref>
                <Button variant="outline" className="w-full justify-between py-6 text-left">
                  <div>
                    <h3 className="font-semibold">{tc('sidebar.mySchedule')}</h3>
                    <p className="text-sm text-muted-foreground">{tc('sidebar.mySchedule')}</p>
                  </div>
                  <ArrowRight />
                </Button>
              </Link>
              <Link href="/request-ride" passHref>
                <Button variant="outline" className="w-full justify-between py-6 text-left">
                  <div>
                    <h3 className="font-semibold">{tc('sidebar.rideRequest')}</h3>
                    <p className="text-sm text-muted-foreground">{tc('sidebar.rideRequest')}</p>
                  </div>
                  <ArrowRight />
                </Button>
              </Link>
            </CardContent>
          </Card>
        </>
      )}

      {user.role === "admin" && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><UserCog className="text-primary" />{tc('sidebar.userManagement')}</CardTitle>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Link href="/admin/vehicles" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                    <h3 className="font-semibold">{tc('sidebar.vehicleManagement')}</h3>
                    <p className="text-sm text-muted-foreground">{tc('sidebar.vehicleManagement')}</p>
                </div>
                <BusFront />
              </Button>
            </Link>
            <Link href="/admin/users" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                    <h3 className="font-semibold">{tc('sidebar.userManagement')}</h3>
                    <p className="text-sm text-muted-foreground">{tc('sidebar.userManagement')}</p>
                </div>
                <UserCog />
              </Button>
            </Link>
            <Link href="/admin/ride-requests" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                    <h3 className="font-semibold">{tc('sidebar.rideRequests')}</h3>
                    <p className="text-sm text-muted-foreground">{t('rideRequests')}</p>
                </div>
                <CalendarCheck />
              </Button>
            </Link>
            <Link href="/admin/settings" passHref>
              <Button variant="outline" className="w-full justify-between py-6 text-left">
                <div>
                    <h3 className="font-semibold">{tc('sidebar.settings')}</h3>
                    <p className="text-sm text-muted-foreground">{tc('sidebar.settings')}</p>
                </div>
                <SettingsIcon />
              </Button>
            </Link>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
