
// This is an autogenerated file.
"use client";

import type { User } from "@/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { FilePenLine, Edit, Search, Upload } from "lucide-react";
import React, { useEffect, useState } from "react";
import { getUsers as dbGetUsers } from "@/lib/database";
import Link from "next/link";
import { useRouter } from "next/navigation"; // Import useRouter for navigation


export default function AdminStudentSchedulesPage() {
  const [students, setStudents] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const router = useRouter(); // Initialize router

  useEffect(() => {
    setIsLoading(true);
    const loadStudents = async () => {
      try {
        const allUsers = await dbGetUsers();
        const studentUsers = allUsers.filter(user => user.role === "student");
        setStudents(studentUsers);
      } catch (error) {
        console.error("Error loading students:", error);
      } finally {
        setIsLoading(false);
      }
    };
    loadStudents();
  }, []);

  const filteredStudents = students.filter(student =>
    student.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (student.studentNumber && student.studentNumber.toLowerCase().includes(searchTerm.toLowerCase())) ||
    student.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2"><FilePenLine className="text-primary" />Öğrenci Ders Programları</CardTitle>
            <CardDescription>Öğrenci ders programları yükleniyor...</CardDescription>
          </CardHeader>
          <CardContent>
            <p>Lütfen bekleyin...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Card className="shadow-lg">
        <CardHeader>
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <CardTitle className="text-2xl flex items-center gap-2"><FilePenLine className="text-primary" />Öğrenci Ders Programı Yönetimi</CardTitle>
              <CardDescription>
                Öğrencilerin haftalık ders programlarını görüntüleyin, düzenleyin veya toplu olarak yükleyin.
              </CardDescription>
            </div>
            <Button onClick={() => router.push('/admin/schedules/bulk-upload')}>
              <Upload className="mr-2 h-4 w-4" /> Toplu Program Yükle/Yönet
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="mb-4">
            <div className="relative">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Ad, Öğrenci No veya E-posta ile Ara..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-8 w-full md:w-1/3 lg:w-1/4"
              />
            </div>
          </div>

          {students.length === 0 ? (
            <div className="my-6 p-4 border border-dashed rounded-lg aspect-video bg-muted flex flex-col items-center justify-center">
              <FilePenLine className="h-16 w-16 text-muted-foreground mb-4" />
              <p className="text-muted-foreground">Sistemde kayıtlı öğrenci bulunmamaktadır.</p>
            </div>
          ) : filteredStudents.length === 0 ? (
            <div className="my-6 p-4 border border-dashed rounded-lg aspect-video bg-muted flex flex-col items-center justify-center">
              <Search className="h-16 w-16 text-muted-foreground mb-4" />
              <p className="text-muted-foreground">Arama kriterlerinize uygun öğrenci bulunamadı.</p>
            </div>
          ) : (
            <div className="border rounded-lg">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Ad Soyad</TableHead>
                    <TableHead>Öğrenci No</TableHead>
                    <TableHead>E-posta</TableHead>
                    <TableHead className="text-right">İşlemler</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredStudents.map((student) => (
                    <TableRow key={student.id}>
                      <TableCell className="font-medium">{student.name}</TableCell>
                      <TableCell>{student.studentNumber || "-"}</TableCell>
                      <TableCell>{student.email}</TableCell>
                      <TableCell className="text-right">
                        <Button variant="outline" size="sm" asChild>
                          <Link href={`/admin/schedules/${student.id}/edit`}>
                            <Edit className="mr-2 h-4 w-4" /> Programı Düzenle
                          </Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
