
// This is an autogenerated file from Firebase Studio.
"use client";

import type { User } from "@/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Input } from "@/components/ui/input"; 
import { FilePenLine, Edit, Search, Upload } from "lucide-react"; 
import React, { useEffect, useState } from "react";
import { getUsers as dbGetUsers } from "@/lib/mock-database";
import Link from "next/link";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";

export default function AdminStudentSchedulesPage() {
  const [students, setStudents] = useState<User[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [isBulkUploadDialogOpen, setIsBulkUploadDialogOpen] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    setIsLoading(true);
    const allUsers = dbGetUsers();
    const studentUsers = allUsers.filter(user => user.role === "student");
    setStudents(studentUsers);
    setIsLoading(false);
  }, []);

  const filteredStudents = students.filter(student =>
    student.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (student.studentNumber && student.studentNumber.toLowerCase().includes(searchTerm.toLowerCase())) ||
    student.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleBulkUpload = () => {
    // In a real app, this would handle file processing.
    // For now, just show a toast.
    toast({
      title: "Toplu Yükleme Başlatıldı (Simülasyon)",
      description: "Dosya seçildi ve işleniyor. Bu özellik yakında tam olarak aktif olacaktır.",
    });
    setIsBulkUploadDialogOpen(false);
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="text-2xl flex items-center gap-2"><FilePenLine className="text-primary"/>Öğrenci Ders Programları</CardTitle>
            <CardDescription>Öğrenci ders programları yükleniyor...</CardDescription>
          </CardHeader>
          <CardContent>
            <p>Lütfen bekleyin...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <Card className="shadow-lg">
        <CardHeader>
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <CardTitle className="text-2xl flex items-center gap-2"><FilePenLine className="text-primary"/>Öğrenci Ders Programı Yönetimi</CardTitle>
              <CardDescription>
                Öğrencilerin haftalık ders programlarını görüntüleyin, düzenleyin veya toplu olarak yükleyin.
              </CardDescription>
            </div>
            <Dialog open={isBulkUploadDialogOpen} onOpenChange={setIsBulkUploadDialogOpen}>
              <DialogTrigger asChild>
                <Button>
                  <Upload className="mr-2 h-4 w-4" /> Toplu Program Yükle
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-[525px]">
                <DialogHeader>
                  <DialogTitle>Toplu Ders Programı Yükle</DialogTitle>
                  <DialogDescription>
                    Öğrenci ders programlarını içeren bir CSV dosyası seçin. Dosya formatı: Öğrenci No, Gün (örn: monday), Ders Kodu, Başlangıç Saati (SS:DD), Bitiş Saati (SS:DD), Konum (Dudullu/Çengelköy).
                  </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                  <div className="grid grid-cols-4 items-center gap-4">
                    <label htmlFor="scheduleFile" className="text-right col-span-1">
                      Dosya:
                    </label>
                    <Input id="scheduleFile" type="file" accept=".csv" className="col-span-3" />
                  </div>
                  <p className="text-xs text-muted-foreground px-1">
                    Örnek CSV satırı: <br />
                    `202003002001,monday,MAT101,09:00,11:00,Dudullu`
                  </p>
                </div>
                <DialogFooter>
                  <DialogClose asChild>
                    <Button type="button" variant="outline">
                      İptal
                    </Button>
                  </DialogClose>
                  <Button type="button" onClick={handleBulkUpload}>Yükle ve İşle</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </CardHeader>
        <CardContent>
          <div className="mb-4">
            <div className="relative">
              <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
              <Input
                type="search"
                placeholder="Ad, Öğrenci No veya E-posta ile Ara..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-8 w-full md:w-1/3 lg:w-1/4"
              />
            </div>
          </div>

          {students.length === 0 ? (
            <div className="my-6 p-4 border border-dashed rounded-lg aspect-video bg-muted flex flex-col items-center justify-center">
              <FilePenLine className="h-16 w-16 text-muted-foreground mb-4" />
              <p className="text-muted-foreground">Sistemde kayıtlı öğrenci bulunmamaktadır.</p>
            </div>
          ) : filteredStudents.length === 0 ? (
             <div className="my-6 p-4 border border-dashed rounded-lg aspect-video bg-muted flex flex-col items-center justify-center">
              <Search className="h-16 w-16 text-muted-foreground mb-4" />
              <p className="text-muted-foreground">Arama kriterlerinize uygun öğrenci bulunamadı.</p>
            </div>
          ) : (
            <div className="border rounded-lg">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Ad Soyad</TableHead>
                    <TableHead>Öğrenci No</TableHead>
                    <TableHead>E-posta</TableHead>
                    <TableHead className="text-right">İşlemler</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filteredStudents.map((student) => (
                    <TableRow key={student.id}>
                      <TableCell className="font-medium">{student.name}</TableCell>
                      <TableCell>{student.studentNumber || "-"}</TableCell>
                      <TableCell>{student.email}</TableCell>
                      <TableCell className="text-right">
                        <Button variant="outline" size="sm" asChild>
                          <Link href={`/admin/schedules/${student.id}/edit`}>
                            <Edit className="mr-2 h-4 w-4" /> Programı Düzenle
                          </Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

