// This is an autogenerated file.
'use server';

/**
 * @fileOverview Analyzes a student's weekly schedule and suggests optimal shuttle pickup and drop-off times.
 *
 * - analyzeSchedule - A function that analyzes the schedule and suggests optimal pickup/drop-off times.
 * - ScheduleAnalyzerInput - The input type for the analyzeSchedule function.
 * - ScheduleAnalyzerOutput - The return type for the analyzeSchedule function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const ScheduleAnalyzerInputSchema = z.object({
  schedule: z
    .string()
    .describe(
      'The student schedule, including course names, start times, end times, and locations.'
    ),
  homeLocation: z
    .string()
    .describe(
      'The student home location, including address that can be used in google maps.'
    ),
  adminDefinedNotificationTime: z.string().describe('Admin defined time for sending notifications'),
  arrivalNotificationTemplate: z.string().describe('Notification template for arrival'),
  departureNotificationTemplate: z.string().describe('Notification template for departure'),
  departureReminderTime: z.string().describe('Admin defined time for departure reminder'),
});
export type ScheduleAnalyzerInput = z.infer<typeof ScheduleAnalyzerInputSchema>;

const ScheduleAnalyzerOutputSchema = z.object({
  pickupTime: z.string().describe('The suggested pickup time for the student.'),
  dropoffTime: z.string().describe('The suggested drop-off time for the student.'),
  notificationMessage: z
    .string()
    .describe('Notification message to send to student.'),
});
export type ScheduleAnalyzerOutput = z.infer<typeof ScheduleAnalyzerOutputSchema>;

export async function analyzeSchedule(input: ScheduleAnalyzerInput): Promise<ScheduleAnalyzerOutput> {
  return analyzeScheduleFlow(input);
}

const analyzeSchedulePrompt = ai.definePrompt({
  name: 'analyzeSchedulePrompt',
  input: { schema: ScheduleAnalyzerInputSchema },
  output: { schema: ScheduleAnalyzerOutputSchema },
  prompt: `You are a university transportation assistant. Analyze the student's schedule and home location, and considering the admin defined notification time, suggest the best pickup and drop-off times, then generate a notification message for the student.

Student Schedule: {{{schedule}}}
Student Home Location: {{{homeLocation}}}
Admin Notification Time: {{{adminDefinedNotificationTime}}}
Arrival Notification Template: {{{arrivalNotificationTemplate}}}
Departure Notification Template: {{{departureNotificationTemplate}}}
Departure Reminder Time: {{{departureReminderTime}}}

Consider:
- Travel time from the student's home to the university.
- Potential delays due to traffic.
- Time needed for the student to get to class after arriving at the university and from the class to the pickup location.
- Time before departure to send the notification.

Suggest:
- pickupTime: The best pickup time for the student.
- dropoffTime: The best drop-off time for the student.
- notificationMessage: A message to send to the student with the pickup and drop-off times.  Use the provided arrivalNotificationTemplate and departureNotificationTemplate to format the notification messages.`,
});

const analyzeScheduleFlow = ai.defineFlow(
  {
    name: 'analyzeScheduleFlow',
    inputSchema: ScheduleAnalyzerInputSchema,
    outputSchema: ScheduleAnalyzerOutputSchema,
  },
  async input => {
    const { output } = await analyzeSchedulePrompt(input);
    return output!;
  }
);
